
name: test_build_and_release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Instrument Build
        uses: kvrhdn/gha-buildevents@main
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: builds
          job-status: ${{ job.status }}

      - run: |
          echo ::set-env name=STEP_ID::0
          echo ::set-env name=STEP_START::$(date +%s)

      - name: Mount Bazelisk Cache
        id: bazelisk-cache
        uses: actions/cache@v2
        with:
          path: |
            - /home/runner/.cache/bazelisk
            - /usr/local/bin/bazel
          key: bazelisk-cache-${{ hashFiles('.bazeliskversion') }}

      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'Mount Bazelisk Cache'

      - run: |
          echo ::set-env name=STEP_ID::1
          echo ::set-env name=STEP_START::$(date +%s)

      - name: Install Bazelisk
        if: steps.bazelisk-cache.outputs.cache-hit != 'true'
        uses: vsco/bazelisk-action@master
        with:
          version: '1.6.1'
          bazel-install-path: './.local/bin'
          os: 'linux'

      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'Install Bazelisk'

      - run: |
          echo ::set-env name=STEP_ID::2
          echo ::set-env name=STEP_START::$(date +%s)

      - name: Mount Bazel Cache
        uses: actions/cache@v2
        with:
          path: |
            - /home/runner/.cache/bazel/_bazel_runner/cache/repos/v1
            - /home/runner/.cache/bazel-disk-cache
          key: bazel-cache- ${{ hashFiles('.bazelversion', 'WORKSPACE') }}

      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'Mount Bazel Cache'

      - run: |
          echo ::set-env name=STEP_ID::3
          echo ::set-env name=STEP_START::$(date +%s)

      - name: Build Linux Artifact
        run: |
          buildevents cmd $TRACE_ID $STEP_ID 'bazel build --disk_cache=/home/runner/.cache/bazel-disk-cache --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64' -- bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //packages/serialized-jira:serialized-jira-linux

      - name: Build Mac Artifact
        run: |
          buildevents cmd $TRACE_ID $STEP_ID 'bazel build --disk_cache=/home/runner/.cache/bazel-disk-cache --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64' -- bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //packages/serialized-jira:serialized-jira-mac

      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'Build Artifacts'

      - run: |
          echo ::set-env name=STEP_ID::4
          echo ::set-env name=STEP_START::$(date +%s)

      - name: Move Artifacts to Working Directory
        run: |
          buildevents cmd $TRACE_ID $STEP_ID 'mv bazel-bin/packages/serialized-jira/serialized-jira_* ./.github/workflows/' -- mv bazel-bin/packages/serialized-jira/serialized-jira_* ./.github/workflows/

      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'Move Artifacts to Working Directory'

      - run: |
          echo ::set-env name=STEP_ID::5
          echo ::set-env name=STEP_START::$(date +%s)

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'Setup Node.js'

      - run: |
          echo ::set-env name=STEP_ID::6
          echo ::set-env name=STEP_START::$(date +%s)

	    - name: Mount Node Modules Cache
        uses: actions/cache@v1
        id: node-cache
        with:
          path: node_modules
          key: package - ${{ hashFiles('package.json') }}

      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'Mount Node Modules Cache'
        
      - run: |
          echo ::set-env name=STEP_ID::7
          echo ::set-env name=STEP_START::$(date +%s)

      - name: Setup Conventional Commits Plugin
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: buildevents cmd $TRACE_ID $STEP_ID 'npm install conventional-changelog-conventionalcommits' -- npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows

      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'Install Conventional Commits Plugin'

      - run: |
          echo ::set-env name=STEP_ID::8
          echo ::set-env name=STEP_START::$(date +%s)

      - name: Release Artifacts to Github
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: naiduarvind
          GIT_AUTHOR_EMAIL: arvind@thebility.engineer
          GIT_COMMITTER_NAME: naiduarvind
          GIT_COMMITTER_EMAIL: arvind@thebility.engineer
        run: npx semantic-release

      - run: |
          buildevents step $TRACE_ID $STEP_ID $STEP_START 'Release Artifacts to Github'