
name: test_build_and_release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Instrument Build
        uses: kvrhdn/gha-buildevents@main
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: builds
          job-status: ${{ job.status }}

      - name: Mount Build Cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install Bazelisk
        uses: vsco/bazelisk-action@master
        with:
          version: '1.5.0'
          bazel-install-path: './.local/bin'
          os: 'linux'

      - name: Build Linux Artifact
        run: |
          bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //packages/serialized-jira:serialized-jira-linux

      - name: Build Mac Artifact
        run: |
          bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //packages/serialized-jira:serialized-jira-mac

      # - name: Upload Artifacts
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: bazel-bin/packages/serialized-jira/serialized-jira_/serialized-jira
      #     asset_name: serialized-jira
      #     tag: ${{ github.ref }}
      #     overwrite: true
      #     body: "Test Github Release with Github Actions"