
name: test_build_and_release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Mount Build Cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install Bazelisk
        uses: vsco/bazelisk-action@master
        with:
          version: '1.5.0'
          bazel-install-path: './.local/bin'
          os: 'linux'

      - name: Build Artifacts
        run: |
          "${GITHUB_WORKSPACE}/bin/bazelisk" build //...

      - name: Upload Artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '${GITHUB_WORKSPACE}/bazel-out/darwin-fastbuild/bin/packages/serialized-jira/serialized-jira_/serialized-jira'